import { createNeural, makeVocab } from '../algorithms/neural.js';
import { tokenize, validateSequence } from '../data/datasets.js';
import { store } from '../data/store.js';
import { run } from '../runtime/client.js';
import { fingerprint } from '../core/math.js';
import { matrixHTML, legend, barsHTML } from '../viz/charts.js';
import { panel, field, select, number, button, note, fmt, escapeHTML, getNumber, inspect, safe, notify } from '../components/ui.js';
export async function mountCNN(root,context){
  const incoming=store.incoming?.type==='explain'&&store.incoming.model.algorithm==='CNN'?store.incoming:null;if(incoming)store.incoming=null;
  const config=incoming?{text:incoming.sample.text,modelSource:'linked',dim:incoming.model.structure.dim,widths:incoming.model.structure.widths.join(','),filters:incoming.model.structure.filters,seed:incoming.model.seed??42,model:incoming.model,method:incoming.model.method,tokens:incoming.sample.tokens}:store.configs.cnn??{text:'这部电影故事精彩，我很喜欢',modelSource:'trained',dim:4,widths:'2,3',filters:2,seed:42,method:'character'};
  let current=incoming?null:store.results.cnn,kernel=0,window=0,poolSelection=0;
  root.innerHTML=`<div class="lab-layout"><section class="controls panel"><div class="control-heading"><span class="eyebrow">EXPERIMENT SETUP</span><h2>让局部特征发声</h2></div>${field('输入文本',`<textarea id="cnn-text" rows="4">${escapeHTML(config.text)}</textarea>`,'最多128 Token；短于卷积宽度时显式右侧补零。')}${field('模型来源',select('cnn-source',[['trained','已训练 Text-CNN · 原模型权重'],['teaching','教学初始化 · 可调整结构'],...(incoming||config.modelSource==='linked'?[['linked','跨模块传入 · 同一模型']]:[])],config.modelSource))}${field('Embedding 维度',number('cnn-dim',config.dim,1,32))}${field('卷积窗口宽度',`<input id="cnn-widths" value="${escapeHTML(config.widths)}" placeholder="2,3,4">`,'逗号分隔整数，1–8，最多四种窗口。')}${field('每种窗口的核数',number('cnn-filters',config.filters,1,8))}${field('随机种子',number('cnn-seed',config.seed,0,2147483647))}${button('计算卷积与分类','cnn-run','primary full','play')}<div class="divider"></div><h3>编辑当前卷积核</h3>${field('核元素索引',number('kernel-index',0,0,255))}${field('权重值',number('kernel-value',.2,-10,10,.01))}${button('应用权重并重算','kernel-apply','full','cnn')}${button('送入此模型评测','cnn-send','full','arrow')}${note('已训练模型的卷积层与分类层均经过 SGD 更新。任意权重修改会产生新模型版本，并使旧评测失效。')}</section><div class="workspace"><div class="flow-strip"><span class="flow-active">01 Embedding</span><i>→</i><span>02 多窗口卷积</span><i>→</i><span>03 ReLU / max</span><i>→</i><span>04 分类</span></div><div id="cnn-result"></div></div></div>`;
  const out=root.querySelector('#cnn-result');
  function featureInspect(index,position,pool=false){poolSelection=index;kernel=index;const f=current.trace.features[index],t=pool?f.winner:position;window=t;const d=current.model.structure.dim,values=Array.from({length:f.width},(_,w)=>current.trace.embedding[t+w]??Array(d).fill(0)),products=values.flatMap((row,w)=>row.map((v,j)=>v*f.weights[w*d+j]));inspect({title:pool?`池化值 · 窗口${f.width} / 核${f.filter+1}`:`卷积激活 · 起点${t+1}`,value:pool?f.value:f.activations[t],formula:'zₜ = ΣᵢΣd Kᵢd Eₜ₊ᵢ,d + b；aₜ = max(0,zₜ)；p = maxₜ aₜ',inputs:{windowTokens:current.tokens.slice(t,t+f.width),embeddingWindow:values,kernel:f.weights,bias:f.bias,products,raw:f.raw[t],activation:f.activations[t],poolingIndex:f.winner},shape:`K∈ℝ${f.width}×${d}，沿 Token 轴滑动`,source:`模型 ${current.model.id} → Embedding → 起点 ${t+1} 窗口 → ReLU → ${pool?'max-over-time winner':'激活'}`});draw();}
  function draw(){if(!current)return;const r=current.trace,m=current.model;kernel=Math.min(kernel,r.features.length-1);const f=r.features[kernel];window=Math.min(window,f.activations.length-1);const base=store.baselines.cnn;
    out.innerHTML=`${panel('文本与词向量矩阵','点击 Token 定位卷积窗口；当前窗口以棕色边框高亮。',`<div class="token-strip">${current.tokens.map((t,i)=>`<button class="token ${i>=window&&i<window+f.width?'selected':''}" data-token="${i}">${escapeHTML(t)}</button>`).join('')}</div>${matrixHTML(r.embedding.slice(Math.max(0,window-2),window+f.width+2),{rows:current.tokens.slice(Math.max(0,window-2),window+f.width+2),id:'cnn-embedding',maxCols:8})}<div class="model-origin">${escapeHTML(m.source)} · ${m.id} · OOV ${r.oov}/${current.tokens.length} · dim=${m.structure.dim}</div>`, `<span class="badge">${m.trained?'TRAINED':'TEACHING'}</span>`)}<div class="two-col">${panel('卷积核 · 覆盖全部 Embedding 维度',`当前宽度 ${f.width}，核 ${f.filter+1}；bias=${fmt(f.bias)}`,`<div class="filter-row"><label for="cnn-kernel" class="small">选择核</label><select id="cnn-kernel">${r.features.map((f,i)=>`<option value="${i}" ${i===kernel?'selected':''}>宽度 ${f.width} · 核 ${f.filter+1}</option>`).join('')}</select></div>${matrixHTML(Array.from({length:f.width},(_,i)=>f.weights.slice(i*m.structure.dim,(i+1)*m.structure.dim)),{rows:Array.from({length:f.width},(_,i)=>`位置 ${i+1}`),id:'cnn-kernel-table',maxCols:8})}<div class="inline-actions">${button('上一个窗口','cnn-prev','','reset')}${button('下一个窗口','cnn-next','','arrow')}${button('检查本次乘加','cnn-inspect','','search')}</div>`)}${panel('特征图 · 原始卷积 → ReLU',`${f.activations.length} 个有效窗口；短文本只补到当前窗口宽度，无纯 padding 窗口。`,matrixHTML([f.raw,f.activations],{rows:['zₜ','ReLU'],cols:f.activations.map((_,i)=>`起点 ${i+1}`),id:'cnn-map',offsetCol:Math.floor(window/8)*8,maxCols:8,selected:[1,window]})+legend(false))}</div>${panel('Max-over-time pooling','点击一个池化值，直接回到产生它的卷积窗口与核。',`<div class="inline-actions">${r.features.map((f,i)=>`<button class="prediction-card ${poolSelection===i?'selected':''}" data-pool="${i}"><h3>k=${f.width} · 核${f.filter+1}</h3><strong>${fmt(f.value,5)}</strong><p>argmax 起点 ${f.winner+1}</p></button>`).join('')}</div>`)}${panel('分类概率 · Softmax(C·pool + b)','类别顺序固定；概率未经校准，不等于可靠置信度。',barsHTML(r.probabilities,m.classes,{id:'cnn-probabilities'})+`<div class="model-origin">logits [${r.logits.map(v=>fmt(v,5)).join(', ')}] · 预测 ${escapeHTML(m.classes[r.prediction])}</div>`)}<details class="panel details-panel"><summary>分类层权重与拼接向量</summary>${matrixHTML([r.pooled],{rows:['concat(pool)'],id:'cnn-pooled'})}${matrixHTML([m.weights.C.slice(0,r.pooled.length),m.weights.C.slice(r.pooled.length)],{rows:m.classes,id:'cnn-classifier'})}</details>${base?panel('A / B · 卷积与分类对照',context.configDiff(base.config,current.config),`<div class="panel-body"><p class="small">模型 A ${base.result.model.id} / B ${m.id}；相同模型不变时为输入干预，改核会生成新权重版本。</p>${barsHTML(r.probabilities.map((v,i)=>Math.abs(v-base.result.trace.probabilities[i])),m.classes,{id:'cnn-delta'})}<p class="small">Δ概率 B−A = [${r.probabilities.map((v,i)=>fmt(v-base.result.trace.probabilities[i],6)).join(', ')}]，完整向量见导出。</p></div>`):''}`;
    out.querySelector('#cnn-kernel').onchange=e=>{kernel=+e.target.value;window=0;draw();};out.querySelector('#cnn-prev').onclick=()=>{window=Math.max(0,window-1);draw();};out.querySelector('#cnn-next').onclick=()=>{window=Math.min(f.activations.length-1,window+1);draw();};out.querySelector('#cnn-inspect').onclick=()=>featureInspect(kernel,window);
    out.querySelectorAll('[data-token]').forEach(el=>el.onclick=()=>{window=Math.min(+el.dataset.token,f.activations.length-1);draw();});out.querySelectorAll('#cnn-map .matrix-cell').forEach(el=>el.onclick=()=>featureInspect(kernel,+el.dataset.col));out.querySelectorAll('[data-pool]').forEach(el=>el.onclick=()=>featureInspect(+el.dataset.pool,0,true));out.querySelectorAll('#cnn-kernel-table .matrix-cell').forEach(el=>el.onclick=()=>{const index=+el.dataset.row*m.structure.dim+(+el.dataset.col);root.querySelector('#kernel-index').value=index;root.querySelector('#kernel-value').value=f.weights[index];inspect({title:`K[${el.dataset.row},${el.dataset.col}]`,value:f.weights[index],formula:'卷积窗口内 Kᵢd × Eₜ₊ᵢ,d',inputs:{kernel:f.weights,window:current.tokens.slice(window,window+f.width)},shape:`${f.width}×${m.structure.dim}`,source:`${m.id} 卷积核${f.kernel}/${f.filter}；可在左侧显式修改并重算`});});out.querySelectorAll('#cnn-probabilities .bar-row').forEach(el=>el.onclick=()=>{const i=+el.dataset.index;inspect({title:`分类概率 · ${m.classes[i]}`,value:r.probabilities[i],formula:'logits=C·concat(pool)+b；p=softmax(logits)',inputs:{pooled:r.pooled,classifier:m.weights.C,bias:m.weights.bC,logits:r.logits},shape:'类别顺序 [0,1]',source:`${m.id} 真实卷积与池化输出`});});
  }
  function modeControls(){const locked=root.querySelector('#cnn-source').value!=='teaching';for(const id of ['cnn-dim','cnn-widths','cnn-filters','cnn-seed'])root.querySelector(`#${id}`).disabled=locked;}
  async function compute(model,text){root.querySelector('#cnn-dim').value=model.structure.dim;root.querySelector('#cnn-widths').value=model.structure.widths.join(',');root.querySelector('#cnn-filters').value=model.structure.filters;const tokens=text===config.text&&config.tokens?config.tokens:tokenize(text,model.method);validateSequence(tokens,128);const trace=await run('explain',{model,tokens,options:{trace:true,target:incoming?.sample.label??config.target??0}});Object.assign(config,{text,model,method:model.method,tokens,dim:model.structure.dim,widths:model.structure.widths.join(','),filters:model.structure.filters,seed:model.seed??42});current={model,trace,tokens,text,config:structuredClone(config)};store.results.cnn=current;store.configs.cnn=structuredClone(config);context.setExperiment(config,current,draw);draw();}
  async function execute(){const text=root.querySelector('#cnn-text').value,source=root.querySelector('#cnn-source').value;config.modelSource=source;let model;if(source==='trained'){model=store.models?.CNN;if(!model)throw new Error('尚无训练模型，请先在多模型工作台训练');}else if(source==='linked'){model=config.model;}else{const widths=root.querySelector('#cnn-widths').value.split(',').map(Number);if(widths.length>4||new Set(widths).size!==widths.length)throw new Error('窗口宽度最多4种且不重复');model=createNeural({algorithm:'CNN',vocab:makeVocab([{tokens:tokenize(text)}]),dim:getNumber('cnn-dim'),widths,filters:getNumber('cnn-filters'),seed:getNumber('cnn-seed')});}await compute(model,text);}
  root.querySelector('#cnn-run').onclick=safe(execute);root.querySelector('#cnn-source').onchange=()=>{modeControls();context.setStatus('stale');};modeControls();
  root.querySelector('#kernel-apply').onclick=safe(async()=>{if(!current)throw new Error('先计算卷积');const model=structuredClone(current.model),f=current.trace.features[kernel],index=getNumber('kernel-index'),value=getNumber('kernel-value'),key=`K${f.kernel}_${f.filter}`;if(index>=model.weights[key].length)throw new Error(`核元素索引范围0–${model.weights[key].length-1}`);model.weights[key][index]=value;model.id=`edited-${fingerprint(model.weights)}`;model.source='显式修改权重的模型；旧评测已失效';config.modelSource='linked';if(!root.querySelector('#cnn-source option[value="linked"]'))root.querySelector('#cnn-source').insertAdjacentHTML('beforeend','<option value="linked">显式编辑模型</option>');root.querySelector('#cnn-source').value='linked';modeControls();await compute(model,root.querySelector('#cnn-text').value);notify('已重新计算，新模型版本独立于旧评测');});
  root.querySelector('#cnn-send').onclick=safe(()=>{if(!current)throw new Error('先计算卷积');store.models??={};store.models.CNN=current.model;store.incoming={type:'model',model:current.model};delete store.results.comparison;location.hash='comparison';notify('同一 Text-CNN 权重送入评测，旧指标已失效');});
  root.querySelectorAll('input,textarea,select').forEach(el=>el.addEventListener('input',()=>context.setStatus('stale')));if(current){context.setExperiment(current.config,current,draw);draw();}else await execute();
}
