import { builtinDataset } from '../data/datasets.js';
import { store } from '../data/store.js';
import { run } from '../runtime/client.js';
import { panel, field, select, button, note, escapeHTML, safe, notify } from '../components/ui.js';
export function mountData(root){
  let parsed=null,candidate=null,fileName='',page=0,revision=0,disposed=false;
  const valid=token=>!disposed&&token===revision;
  root.innerHTML=`<div class="two-col"><section class="panel"><div class="panel-head"><div><h2>导入自己的数据</h2><p>UTF-8 编码 · 完全本地解析 · 不会上传</p></div><span class="badge">TXT / CSV / JSONL</span></div><div class="panel-body"><div class="upload-zone">${'<svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="#548c83" stroke-width="1.4"><path d="M12 16V3m-5 5 5-5 5 5M4 16v5h16v-5"/></svg>'}<h3>选择文本或分类样本</h3><p>目标档10 MiB / 10,000条；允许50 MiB / 50,000条，需结合实测预算。</p><input id="dataset-file" type="file" accept=".txt,.csv,.jsonl,.json" aria-label="选择数据文件"></div>${field('CSV 分隔符',select('delimiter',[[',','逗号 ,'],['\t','制表符 Tab'],[';','分号 ;']],','))}<div id="mapping"></div><div id="data-error" role="alert"></div></div></section>${panel('当前数据集','供词向量与四模型实验共享。',`<div id="active-dataset" class="panel-body"></div>`)}</div><div id="data-preview" style="margin-top:22px"></div>`;
  function active(){const d=store.dataset??builtinDataset;root.querySelector('#active-dataset').innerHTML=`<h3>${escapeHTML(d.name)}</h3><p class="small" style="margin:12px 0">${escapeHTML(d.source)}</p><div class="stat-strip" style="grid-template-columns:repeat(3,1fr)">${['train','validation','test'].map(split=>`<div class="stat"><span>${split}</span><strong>${d.samples.filter(s=>s.split===split).length}</strong></div>`).join('')}</div><p class="small">分词 ${d.method} · 版本 ${d.preprocessing}<br>许可：${escapeHTML(d.license)} · ${d.samples.length} 样本</p><div class="inline-actions" style="padding:20px 0 0"><a class="btn primary" href="#comparison">进入多模型实验</a>${button('恢复内置教学集','restore-data','','reset')}</div>${note('内置56条句子为本项目原创、AI辅助整理的教学材料，不是外部真实评测数据集。固定32/8/16划分。')}`;root.querySelector('#restore-data').onclick=()=>{store.dataset=null;delete store.results.comparison;delete store.configs.comparison;active();notify('已恢复内置数据；模型不会被偷偷替换，需确认兼容或重新训练');};}
  async function preview(token){const options={textField:root.querySelector('#text-field').value,labelField:root.querySelector('#label-field').value,splitField:root.querySelector('#split-field').value,method:root.querySelector('#data-method').value,name:fileName,source:`用户导入：${fileName}`};const result=await run('dataset',{parsed,options});if(!valid(token))return;candidate=result;page=0;draw();}
  function draw(){if(!candidate)return;const d=candidate,labelled=d.samples.filter(s=>s.label!=null),lengths=d.samples.map(s=>s.tokens.length),splits=['train','validation','test'];root.querySelector('#data-preview').innerHTML=panel('预览与校验',`完整解析 ${d.samples.length} 条；展示最多25条。确认后才能参与实验。`, `<div class="stat-strip" style="margin:0 24px 20px"><div class="stat"><span>样本数</span><strong>${d.samples.length}</strong><small>${d.duplicates} 条重复 Token 序列</small></div><div class="stat"><span>带标签</span><strong>${labelled.length}</strong><small>${d.classes.map((l,c)=>`${escapeHTML(l)} ${labelled.filter(s=>s.label===c).length}`).join(' / ')}</small></div><div class="stat"><span>平均 Token 长度</span><strong>${(lengths.reduce((a,b)=>a+b,0)/lengths.length).toFixed(1)}</strong><small>最大 ${lengths.reduce((a,b)=>Math.max(a,b),0)}</small></div><div class="stat"><span>分组划分</span><strong>${splits.map(s=>d.samples.filter(r=>r.split===s).length).join('/')}</strong><small>train / validation / test</small></div></div><div class="panel-body">${note('没有 split 字段时，按 Token 指纹的固定哈希分组划分（约70/10/20）；重复序列不跨集合。近重复模板需用户提供明确分组/划分，自动检查仅覆盖完全重复。')}<p class="small" style="margin:10px 0">长度分布：≤16 ${lengths.filter(n=>n<=16).length}；17–64 ${lengths.filter(n=>n>16&&n<=64).length}；65–128 ${lengths.filter(n=>n>64&&n<=128).length}；>128 ${lengths.filter(n=>n>128).length}。训练/批量推理上限128；超长会拒绝，不默默截断。</p></div><div class="table-wrap"><table class="data-table"><thead><tr><th>ID / split</th><th>文本</th><th>Token / 标签</th></tr></thead><tbody>${d.samples.slice(page*25,page*25+25).map(s=>`<tr><td>${s.id}<br><span class="small">${s.split}</span></td><td>${escapeHTML(s.text)}</td><td>${s.tokens.length} / ${s.label==null?'未标注':escapeHTML(d.classes[s.label])}</td></tr>`).join('')}</tbody></table></div><div class="pagination"><span>第 ${page+1}/${Math.ceil(d.samples.length/25)} 页</span><div>${button('上一页','data-prev','compact')}${button('下一页','data-next','compact')}${button('确认使用数据','confirm-data','primary','check')}</div></div>`);
    root.querySelector('#data-prev').onclick=()=>{page=Math.max(0,page-1);draw();};root.querySelector('#data-next').onclick=()=>{page=Math.min(Math.ceil(d.samples.length/25)-1,page+1);draw();};root.querySelector('#confirm-data').onclick=()=>{store.dataset=d;delete store.results.comparison;delete store.configs.comparison;active();notify('已确认数据；旧评测失效，请检查分词与类别并重新训练');};
  }
  async function parse(token){root.querySelector('#data-error').textContent='';const file=root.querySelector('#dataset-file').files[0];if(!file)return;if(file.size>50*1024*1024)throw new Error('文件超过50MiB，请拆分');fileName=file.name;const delimiter=root.querySelector('#delimiter').value,text=await file.text();if(!valid(token))return;const result=await run('parse',{text,name:file.name,delimiter});if(!valid(token))return;parsed=result;const cols=parsed.columns.map(c=>[c,c]);root.querySelector('#mapping').innerHTML=`<h3 style="margin-bottom:16px">字段映射</h3>${field('文本字段',select('text-field',cols,parsed.columns.includes('text')?'text':parsed.columns[0]))}${field('标签字段 · 可不提供',select('label-field',[['','无标签 / 仅预测'],...cols],parsed.columns.includes('label')?'label':''))}${field('数据划分字段',select('split-field',[['','固定哈希分组划分'],...cols],parsed.columns.includes('split')?'split':''))}${field('确定性分词',select('data-method',[['character','中文字符 + 英文词 · local-v1'],['space','空格预分词 · local-v1']],'character'))}${button('校验并预览','data-validate','primary full','search')}`;root.querySelector('#data-validate').onclick=withError(preview);await preview(token);}
  function invalidate(){revision++;candidate=null;root.querySelector('#data-preview').innerHTML='';}
  function withError(fn){return async()=>{invalidate();const token=revision;try{await fn(token);if(!valid(token))return;root.querySelector('#data-error').textContent='';}catch(e){if(!valid(token))return;invalidate();root.querySelector('#data-error').innerHTML=`<div class="note" style="color:#a5392d;background:#fff4ee;margin-top:16px">${escapeHTML(e.message)}</div>`;notify(e.message,true);}};}
  root.querySelector('#mapping').addEventListener('input',invalidate);
  const reload=withError(async token=>{parsed=null;root.querySelector('#mapping').innerHTML='';await parse(token);});
  root.querySelector('#dataset-file').onchange=reload;root.querySelector('#delimiter').onchange=reload;active();return()=>{disposed=true;revision++;};
}
