import { store, persist } from '../data/store.js';
import { validateExperiment } from '../data/validation.js';
import { modules } from '../app/catalog.js';
import { VERSION, fingerprint } from '../core/math.js';
import { panel, field, button, note, escapeHTML, download, safe, notify } from '../components/ui.js';
export function mountNotebook(root){
  root.innerHTML=`${panel('导入可复现记录','支持由实验页面或笔记导出的版本1 JSON；先校验，再重新执行数学核心。',`<div class="inline-actions"><label class="field" style="margin:0"><span class="field-label">选择实验 JSON</span><input id="experiment-file" type="file" accept=".json" aria-label="选择实验记录"></label></div><div class="panel-body">${note('只保存种子不能保证跨版本重放。神经模型记录保留真实权重，词向量记录保留语料和训练状态；此版本仅重放相同算法版本。文件来源声明不等于验证了其成绩。')}</div>`)}<div id="record-list" style="margin-top:22px"></div>`;
  function replay(r){validateExperiment(r);const c=structuredClone(r.config);if(r.dataReference&&!c.dataset&&r.module==='comparison'){if(!store.dataset||fingerprint(store.dataset.samples)!==r.dataReference.fingerprint)throw new Error(`此记录仅引用数据，请先导入原文件 ${r.dataReference.name}；指纹 ${r.dataReference.fingerprint}`);c.dataset=store.dataset;}if(['sequence','cnn'].includes(r.module)&&c.model)c.modelSource='linked';if(r.module==='comparison'){if(c.dataset)store.dataset=c.dataset;if(c.models)store.models=c.models;store.incoming={type:'replay'};}store.configs[r.module]=c;store.results[r.module]=null;location.hash=r.module;notify('已载入原输入、权重与配置，正在重新计算');}
  function draw(){const list=root.querySelector('#record-list');list.innerHTML=store.records.length?store.records.map((r,i)=>panel(escapeHTML(r.name??'未命名实验'),`${modules.find(m=>m.id===r.module)?.full??r.module} · ${r.createdAt?new Date(r.createdAt).toLocaleString('zh-CN'):'导入记录'} · ${r.algorithmVersion}`,`<div class="panel-body"><p class="small">种子 ${r.seed??r.config.seed??42} · 配置指纹 ${r.configFingerprint??fingerprint(r.config)}<br>数据来源 ${escapeHTML(r.dataSource??'记录配置内的数据')}<br>模型 ${escapeHTML(r.modelId??r.config.model?.id??'配置中的教学/训练模型')}</p>${r.notes?`<p style="margin-top:12px;font-size:14px">${escapeHTML(r.notes)}</p>`:''}<div class="inline-actions" style="padding:18px 0 0">${button('重新运行',`replay-${i}`,'primary','play')}${button('固定为 A',`baseline-${i}`,'','compare')}${button('导出完整 JSON',`download-${i}`,'','download')}${r.module==='comparison'?button('仅引用原数据',`reference-${i}`,'','download'):''}</div></div>`)).join(''):panel('开始记下你的发现','你的第一条实验笔记，从一次真实计算开始。','<div class="empty-state"><h3>还没有保存的实验</h3><p>打开任意模块，运行后点击「保存实验」，给这次观察命名。</p><a class="btn primary" href="#attention">进入注意力实验</a></div>');
    store.records.forEach((r,i)=>{list.querySelector(`#replay-${i}`).onclick=safe(()=>replay(r));list.querySelector(`#download-${i}`).onclick=()=>download(`${r.module}-${i+1}.json`,JSON.stringify(r,(_,v)=>typeof v==='number'&&!Number.isFinite(v)?String(v):v,2));list.querySelector(`#baseline-${i}`).onclick=safe(()=>{validateExperiment(r);if(!r.result||r.status!=='completed')throw new Error('导入的成绩尚未核验，请先重新运行，在模块中固定 A');store.baselines[r.module]={config:structuredClone(r.config),result:structuredClone(r.result),fingerprint:fingerprint(r.config)};notify('记录已固定为 A；请重放并改变一个因素');});if(r.module==='comparison')list.querySelector(`#reference-${i}`).onclick=()=>{const copy=structuredClone(r),data=copy.config.dataset;if(data){copy.dataReference={name:data.name,fingerprint:fingerprint(data.samples),required:'需要重新导入原数据文件，匹配相同预处理与样本指纹'};delete copy.config.dataset;if(copy.result)delete copy.result.rows;copy.result=null;}download(`${r.module}-reference.json`,JSON.stringify(copy,null,2));};});
  }
  root.querySelector('#experiment-file').onchange=safe(async e=>{const f=e.target.files[0];if(!f)return;if(f.size>10*1024*1024)throw new Error('实验文件超过10MiB，请使用数据引用方式');const r=validateExperiment(JSON.parse(await f.text()));r.id??=`import-${Date.now()}`;r.name??=`导入 · ${f.name}`;r.createdAt??=new Date().toISOString();r.status='已导入待重放';store.records.unshift(r);persist();draw();notify('JSON 已校验；点击重新运行核对实际结果');});draw();
}
