import { logistic, optimizationData } from '../algorithms/optimization.js';
import { store } from '../data/store.js';
import { run } from '../runtime/client.js';
import { panel, field, number, button, note, getNumber, fmt, inspect, safe, escapeHTML } from '../components/ui.js';
import { curveSVG, contourSVG } from '../viz/charts.js';
export async function mountOptimization(root,context){
  const config=store.configs.optimization??{lr:.1,steps:150,batch:8,seed:42,initial:[0,0],data:optimizationData};let current=store.results.optimization,selected=current?.history.length-1??0;
  root.innerHTML=`<div class="lab-layout"><section class="controls panel"><div class="control-heading"><span class="eyebrow">EXPERIMENT SETUP</span><h2>沿着梯度走一步</h2></div>${field('学习率 · η',`<div class="range-pair"><input id="lr-slider" aria-label="学习率滑块" type="range" min="-3" max="1" step=".05" value="${Math.log10(config.lr)}">${number('lr',config.lr,.0001,100,.001)}</div>`,'滑块为对数刻度；修改后点击运行，从相同初值开始。')}${field('实际更新步数',number('steps',config.steps,1,10000))}${field('批大小',number('batch',config.batch,1,config.data.length))}${field('随机种子',number('seed',config.seed,0,2147483647))}${field('初始 w₁',number('w1',config.initial[0],-100,100,.1))}${field('初始 w₂ · 截距',number('w2',config.initial[1],-100,100,.1))}${button('运行真实训练','opt-run','primary full','play')}<div class="divider"></div><h3>可复现的学习率案例</h3>${button('慢收敛 · η = 0.001','lr-slow','full')}${button('稳步收敛 · η = 0.1','lr-normal','full')}${button('大步长震荡 · η = 8','lr-high','full')}<details><summary>编辑二维训练数据</summary>${field('JSON · [{x:[特征,1],y:0或1}]',`<textarea id="opt-data" rows="6">${escapeHTML(JSON.stringify(config.data))}</textarea>`)}</details>${note('这是两个自由参数的 Logistic 分类器。固定全数据评估损失与训练批损失分别记录；冲突标签意味着最小损失不为零。')}</section><div class="workspace"><div class="flow-strip"><span class="flow-active">01 前向预测</span><i>→</i><span>02 交叉熵</span><i>→</i><span>03 求梯度</span><i>→</i><span>04 SGD 更新</span></div><div id="opt-result"></div></div></div>`;
  const output=root.querySelector('#opt-result');
  function point(i){selected=Math.max(0,Math.min(current.history.length-1,i));const h=current.history[selected];inspect({title:`第 ${h.step} 次更新前的参数与梯度`,value:h.loss,formula:'L = mean(softplus(z) − y·z)；∇L = mean((σ(z)−y)x)；w ← w−η∇L',inputs:{weights:h.w,gradient:h.gradient,learningRate:current.config.lr,nextWeights:h.w.map((v,j)=>v-current.config.lr*h.gradient[j]),trainBatchLoss:h.trainLoss},shape:'w∈ℝ² · 固定评估集平均交叉熵',source:`种子 ${current.config.seed} → 相同样本顺序 → 第 ${h.step} 个真实更新`,detail:'图中是全量固定评估集损失；梯度和 trainBatchLoss 来自当步训练批次。最后一步只评估，未再次更新。'});draw();}
  function draw(){if(!current)return;selected=Math.min(selected,current.history.length-1);const h=current.history[selected],details=logistic(h.w,current.config.data),base=store.baselines.optimization;const series=[{label:`B · η=${current.config.lr}`,values:current.history.map(p=>({x:p.step,y:p.loss}))}];if(base)series.push({label:`A · η=${base.config.lr}`,values:base.result.history.map(p=>({x:p.step,y:p.loss}))});
    output.innerHTML=`<div class="stat-strip"><div class="stat"><span>当前选择 · 实际更新步</span><strong>${h.step}</strong><small>共 ${current.history.length-1} 步</small></div><div class="stat"><span>固定评估集 · CE</span><strong>${fmt(h.loss,5)}</strong><small>natural log</small></div><div class="stat"><span>w₁ · 特征系数</span><strong>${fmt(h.w[0],4)}</strong><small>梯度 ${fmt(h.gradient[0],5)}</small></div><div class="stat"><span>w₂ · 截距</span><strong>${fmt(h.w[1],4)}</strong><small>梯度 ${fmt(h.gradient[1],5)}</small></div></div>${panel('真实迭代的损失轨迹','每个记录点对应一次实际评估。点击曲线或选择步数检查更新。',curveSVG(series)+`<div class="inline-actions"><label class="field" style="margin:0;flex:1"><span class="field-label">检查迭代点 · <b id="step-label">${h.step}</b></span><input id="opt-point" type="range" min="0" max="${current.history.length-1}" value="${selected}" aria-label="检查迭代点"></label>${button('回到初值','opt-rewind','','reset')}${button('查看数值','opt-inspect','','search')}</div>${base?`<div class="comparison-meta">${escapeHTML(context.configDiff(base.config,current.config))}；A/B共享坐标轴。</div>`:''}`,`<span class="badge">${current.history.length} 个真实点</span>`)}<div class="two-col">${panel('二维损失空间','仅 w₁、w₂ 两个自由参数；网格 [-3,3]² 的真实损失。',`<div class="panel-body">${contourSVG(current.config.data,current.history,logistic)}${note('轨迹超出 [-3,3] 的部分不在此视域绘制，可从曲线与原始记录查看完整数值。')}</div>`)}${panel(`逐样本计算 · 第 ${h.step} 步`,'每样本贡献汇总为显示的固定评估集损失。',`<div class="table-wrap"><table class="data-table"><thead><tr><th>x₁ / y</th><th>z</th><th>σ(z)</th><th>CE</th></tr></thead><tbody>${details.rows.map((r,i)=>`<tr><td>${r.x[0]} / ${r.y}</td><td>${fmt(r.z,3)}</td><td>${fmt(r.p,3)}</td><td><button class="btn compact" data-sample="${i}">${fmt(r.loss,4)}</button></td></tr>`).join('')}</tbody></table></div>`)}</div>`;
    output.querySelector('#opt-point').onchange=e=>point(+e.target.value);output.querySelector('#opt-point').oninput=e=>{output.querySelector('#step-label').textContent=e.target.value;};
    output.querySelector('#opt-inspect').onclick=()=>point(selected);output.querySelector('#opt-rewind').onclick=()=>point(0);
    output.querySelector('#curve').onclick=e=>{const bounds=e.currentTarget.getBoundingClientRect(),x=(e.clientX-bounds.left)/bounds.width*800;point(Math.round((x-55)/(800-55-24)*(current.history.length-1)));};
    output.querySelectorAll('[data-sample]').forEach(el=>el.onclick=()=>{const r=details.rows[+el.dataset.sample];inspect({title:`样本 ${+el.dataset.sample+1} 的损失`,value:r.loss,formula:'z=w·x；p=σ(z)；CE=softplus(z)−y·z',inputs:r,shape:'单样本 → 标量损失',source:`当前真实 w=[${h.w.map(v=>fmt(v)).join(', ')}]，标签 y=${r.y}`});});
  }
  async function execute(){config.lr=getNumber('lr');config.steps=getNumber('steps');config.seed=getNumber('seed');config.initial=[getNumber('w1'),getNumber('w2')];config.data=JSON.parse(root.querySelector('#opt-data').value);config.batch=getNumber('batch');current=await run('optimization',structuredClone(config));store.results.optimization=current;store.configs.optimization=structuredClone(config);selected=current.history.length-1;context.setExperiment(config,current,draw);draw();}
  root.querySelector('#opt-run').onclick=safe(execute);root.querySelector('#lr-slider').oninput=e=>{root.querySelector('#lr').value=(10**+e.target.value).toFixed(4);context.setStatus('stale');};root.querySelector('#lr').oninput=e=>{root.querySelector('#lr-slider').value=Math.log10(+e.target.value);context.setStatus('stale');};
  for(const[id,value]of [['lr-slow',.001],['lr-normal',.1],['lr-high',8]])root.querySelector(`#${id}`).onclick=safe(async()=>{root.querySelector('#lr').value=value;root.querySelector('#lr-slider').value=Math.log10(value);root.querySelector('#w1').value=0;root.querySelector('#w2').value=0;root.querySelector('#batch').value=8;root.querySelector('#opt-data').value=JSON.stringify(optimizationData);await execute();});
  root.querySelectorAll('input,textarea').forEach(el=>el.addEventListener('input',()=>context.setStatus('stale')));
  if(current){context.setExperiment(current.config,current,draw);draw();}else await execute();
}
