import { it, expect, describe } from 'vitest';
import { createNeural, neuralForward, trainNeural, validateModel } from '../../src/algorithms/neural.js';
import { consume } from '../../src/runtime/tasks.js';
import { sigmoid } from '../../src/core/math.js';
describe('三序列单元可手算',()=>{
  it('RNN tanh(xW+hU+b)',()=>{const m=createNeural({vocab:['<UNK>','a'],dim:1,hidden:1});m.weights.E=[0,2];m.weights.Wh=[.3];m.weights.Uh=[.4];m.weights.bh=[.1];const r=neuralForward(m,['a','a']);expect(r.states[0].hidden[0]).toBeCloseTo(Math.tanh(.7));expect(r.states[1].hidden[0]).toBeCloseTo(Math.tanh(.7+.4*Math.tanh(.7)));});
  it('LSTM 独立门值与细胞状态',()=>{const m=createNeural({algorithm:'LSTM',vocab:['<UNK>','a'],dim:1,hidden:1});m.weights.E=[0,1];for(const g of ['i','f','o','g']){m.weights['W'+g]=[.2];m.weights['U'+g]=[0];m.weights['b'+g]=[0];}const r=neuralForward(m,['a','a']),c1=sigmoid(.2)*Math.tanh(.2),c2=sigmoid(.2)*c1+c1;expect(r.states[0].cell[0]).toBeCloseTo(c1);expect(r.states[1].hidden[0]).toBeCloseTo(sigmoid(.2)*Math.tanh(c2));});
  it('GRU reset-before，z 保留旧状态',()=>{const m=createNeural({algorithm:'GRU',vocab:['<UNK>','a'],dim:1,hidden:1});m.weights.E=[0,1];for(const g of ['z','r','n']){m.weights['W'+g]=[.2];m.weights['U'+g]=[.3];m.weights['b'+g]=[0];}const r=neuralForward(m,['a','a']),h=(1-sigmoid(.2))*Math.tanh(.2),z=sigmoid(.2+.3*h),reset=sigmoid(.2+.3*h),n=Math.tanh(.2+.3*reset*h);expect(r.states[1].hidden[0]).toBeCloseTo(z*h+(1-z)*n);});
});
it('CNN 真卷积、ReLU、max-over-time 和短序列 padding',()=>{const m=createNeural({algorithm:'CNN',vocab:['<UNK>','a','b','c'],dim:1,widths:[2],filters:1});m.weights.E=[0,1,2,3];m.weights.K0_0=[2,-1];m.weights.bK0_0=[.5];const r=neuralForward(m,['a','b','c']);expect(r.features[0].raw).toEqual([.5,1.5]);expect(r.pooled).toEqual([1.5]);expect(r.features[0].winner).toBe(1);expect(neuralForward(m,['a']).features[0].raw).toEqual([2.5]);});
for(const algorithm of ['RNN','LSTM','GRU','CNN'])it(`${algorithm} 全权重有限差分、推理/可微前向一致`,()=>{const m=createNeural({algorithm,vocab:['<UNK>','a','b'],dim:2,hidden:2,widths:[2],filters:1,seed:9}),tokens=['a','b','a'];if(algorithm==='CNN')m.weights.bK0_0=[1];const r=neuralForward(m,tokens,{gradient:true,target:1}),numeric=neuralForward(m,tokens,{target:1});expect(r.logits).toEqual(numeric.logits);const eps=1e-6;for(const[k,w]of Object.entries(m.weights))for(let i=0;i<w.length;i++){const orig=w[i];w[i]=orig+eps;const a=neuralForward(m,tokens,{target:1}).loss;w[i]=orig-eps;const b=neuralForward(m,tokens,{target:1}).loss;w[i]=orig;expect(Math.abs((a-b)/(2*eps)-r.gradients[k][i])).toBeLessThan(1e-5);}expect(r.stateGradients?.every(s=>s.every(Number.isFinite))??true).toBe(true);});
it('训练卷积/分类层真实改变、可复现、模型形状验证',async()=>{const m=createNeural({algorithm:'CNN',vocab:['<UNK>','a','b'],dim:2,widths:[1,2],filters:2,seed:9}),samples=[{tokens:['a','a'],label:1},{tokens:['b','b'],label:0}];const a=await consume(trainNeural(m,samples,{epochs:2,batch:2})),b=await consume(trainNeural(m,samples,{epochs:2,batch:2}));expect(a.model.weights).toEqual(b.model.weights);expect(a.model.weights.C).not.toEqual(m.weights.C);expect(a.model.weights.K0_0).not.toEqual(m.weights.K0_0);expect(validateModel(a.model)).toBe(a.model);expect(()=>validateModel({...a.model,weights:{}})).toThrow();});
