import { fromProject, evidencePath } from '../../../tools/paths.mjs';
import {test,expect} from '../../../tools/testing/playwright.js';
import {pathToFileURL} from 'node:url';
const capture=async(page,options)=>{await page.evaluate(()=>window.scrollTo(0,0));await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.screenshot({...options,animations:'disabled',style:'#toast{visibility:hidden}'});};
const entry=pathToFileURL(fromProject('release/index.html')).href;
const boot=async(page,id)=>{await page.goto(entry+'#'+id);await expect(page.locator('#result-state')).toHaveText('结果已更新');};
test('M01 三种训练、检索、类比、检查器与 A/B',async({page})=>{
  await boot(page,'embeddings');await expect(page.locator('#embedding-canvas')).toBeVisible();await page.locator('#word-search').fill('语言');await page.getByRole('button',{name:'定位',exact:true}).click();await expect(page.locator('.inspect-content')).toContainText('语言');await page.getByLabel('关闭检查器').click();await page.getByRole('button',{name:'固定为 A'}).click();
  await page.locator('#embedding-algorithm').selectOption('cbow');await page.getByRole('button',{name:'训练词向量'}).click();await expect(page.locator('#result-state')).toHaveText('结果已更新');await expect(page.getByRole('heading',{name:'A / B · 训练对照'})).toBeVisible();await page.locator('#inspect-update').click();await expect(page.locator('.formula')).toContainText('log σ');await page.getByLabel('关闭检查器').click();
  await page.locator('#embedding-algorithm').selectOption('glove');await expect(page.locator('#negative-field')).toBeHidden();await page.getByRole('button',{name:'训练词向量'}).click();await expect(page.locator('#result-state')).toHaveText('结果已更新');await capture(page,{path:evidencePath('embeddings-1440.png'),fullPage:true});
  await page.locator('#word-search').fill('不存在');await page.getByRole('button',{name:'定位',exact:true}).click();await expect(page.locator('#toast')).toContainText('OOV');
});
test('M02 三结构、步进与回退、梯度与长序列',async({page})=>{
  await boot(page,'sequence');await page.locator('#sequence-next').click();await expect(page.locator('#sequence-result')).toContainText('正在观察 第 1 步');await page.locator('#sequence-back').click();await expect(page.locator('#sequence-result')).toContainText('初始状态 h₀=0');
  for(const algorithm of ['LSTM','GRU']){await page.locator('#sequence-algorithm').selectOption(algorithm);await page.locator('#sequence-run').click();await expect(page.locator('#result-state')).toHaveText('结果已更新');await expect(page.locator('#gate-table')).toBeVisible();await page.locator('#sequence-next').click();await page.locator('#current-state .matrix-cell').first().click();await expect(page.locator('.inspect-content')).toContainText('梯度');await page.getByLabel('关闭检查器').click();}
  await capture(page,{path:evidencePath('sequence-1440.png'),fullPage:true});await page.locator('#sequence-long').click();await expect(page.locator('#sequence-result')).toContainText('96 时间步');await page.locator('#sequence-reset').click();await expect(page.locator('#sequence-result')).toContainText('初始状态 h₀=0');
});
test('M03 池化→窗口、改权重→新模型版本',async({page})=>{
  await boot(page,'cnn');await page.locator('[data-pool]').first().click();await expect(page.locator('.inspect-content')).toContainText('poolingIndex');await expect(page.locator('.formula')).toContainText('max');await page.getByLabel('关闭检查器').click();await page.getByRole('button',{name:'固定为 A'}).click();await page.locator('#kernel-index').fill('0');await page.locator('#kernel-value').fill('1.5');await page.locator('#kernel-apply').click();await expect(page.locator('#cnn-result')).toContainText('edited-');await expect(page.getByRole('heading',{name:'A / B · 卷积与分类对照'})).toBeVisible();await capture(page,{path:evidencePath('cnn-1440.png'),fullPage:true});
  await page.locator('#cnn-text').fill('好');await page.locator('#cnn-run').click();await expect(page.locator('#result-state')).toHaveText('结果已更新');await expect(page.locator('#cnn-map .matrix-cell')).toHaveCount(2);
});
test('M05 四模型真实预测、混淆筛选与原权重解释',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));await boot(page,'comparison');await page.locator('#compare-text').fill('这个故事我不喜欢');await page.locator('#compare-predict').click();await expect(page.locator('.compare-grid .prediction-card')).toHaveCount(4);await expect(page.locator('#single-predictions')).toContainText('未校准分数');
  await page.locator('#error-filter').selectOption('errors');await expect(page.locator('#compare-result')).toContainText('筛选');await capture(page,{path:evidencePath('comparison-1440.png'),fullPage:true});
  const id=await page.locator('#compare-result .data-table').first().locator('tbody tr').nth(2).locator('td').last().textContent();await page.locator('[data-explain="RNN"]').first().click();await expect(page.locator('#result-state')).toHaveText('结果已更新');await expect(page.locator('#sequence-result')).toContainText(id.trim());await expect(page.locator('#sequence-source')).toHaveValue('linked');expect(errors).toEqual([]);
});
test('M06 实际曲线、点检查、三学习率与对照',async({page})=>{
  await boot(page,'optimization');await page.locator('#opt-inspect').click();await expect(page.locator('.inspect-content')).toContainText('nextWeights');await page.getByLabel('关闭检查器').click();await page.getByRole('button',{name:'固定为 A'}).click();await page.locator('#lr-high').click();await expect(page.locator('#result-state')).toHaveText('结果已更新');await expect(page.locator('#opt-result')).toContainText('A · η=0.1');await capture(page,{path:evidencePath('optimization-1440.png'),fullPage:true});await page.locator('#opt-rewind').click();await expect(page.locator('#step-label')).toHaveText('0');
});
test('数据 CSV 字段映射、预览确认与错误状态',async({page})=>{
  await page.goto(entry+'#data');await page.locator('#dataset-file').setInputFiles({name:'自己的 样本.csv',mimeType:'text/csv',buffer:Buffer.from('text,label,split\n很好,正,train\n糟糕,负,train\n好看,正,validation\n不好,负,validation\n喜欢,正,test\n讨厌,负,test')});await expect(page.locator('#data-preview')).toContainText('完整解析 6 条');await capture(page,{path:evidencePath('data-import-1440.png'),fullPage:true});await page.locator('#confirm-data').click();await expect(page.locator('#active-dataset')).toContainText('自己的 样本.csv');
  await page.locator('#label-field').selectOption('');await expect(page.locator('#data-preview')).toBeEmpty();await page.locator('#label-field').selectOption('label');await page.locator('#data-validate').click();await expect(page.locator('#confirm-data')).toBeVisible();
  await page.locator('#dataset-file').setInputFiles({name:'broken.csv',mimeType:'text/csv',buffer:Buffer.from('text,label\n"未闭合,0')});await expect(page.locator('#data-error')).toContainText('引号');await expect(page.locator('#confirm-data')).toHaveCount(0);await expect(page.locator('#data-preview')).toBeEmpty();await capture(page,{path:evidencePath('data-error.png'),fullPage:true});
  await page.locator('.nav-link[href="#comparison"]').click();await expect(page.locator('#page-root')).toContainText('不兼容');await expect(page.locator('#compare-train')).toBeVisible();await page.locator('#compare-epochs').fill('2');await page.locator('#compare-train').click();await expect(page.locator('#result-state')).toHaveText('结果已更新');await expect(page.locator('#compare-result')).toContainText('2 条完整计算');
});
test('I04 保存、导出、导入与重放',async({page})=>{
  await boot(page,'attention');await page.getByRole('button',{name:'保存实验'}).click();await page.locator('#record-name').fill('掩码对照可复现实验');await page.locator('#record-notes').fill('注意观察每行权重和。');await page.locator('#modal-save').click();await page.goto(entry+'#notebook');await expect(page.locator('#record-list')).toContainText('掩码对照可复现实验');
  const wait=page.waitForEvent('download');await page.locator('#download-0').click();const f=await wait;const path=await f.path();await page.locator('#experiment-file').setInputFiles(path);await expect(page.locator('#record-list > .panel')).toHaveCount(2);await page.locator('#replay-0').click();await expect(page.locator('#result-state')).toHaveText('结果已更新');await expect(page.locator('#matrix .matrix-cell')).toHaveCount(20);
});
test('I03 向量快照→同一 RNN/CNN→批量评测',async({page})=>{
  await boot(page,'embeddings');await page.locator('#send-embedding').click();await expect(page.locator('#use-embedding')).toBeChecked();await page.locator('#embedding-remap').check();await page.locator('#compare-epochs').fill('2');await page.locator('#compare-train').click();await expect(page.locator('#result-state')).toHaveText('结果已更新');await expect(page.locator('#compare-result')).toContainText('RNN-');await page.locator('[data-explain="CNN"]').first().click();await expect(page.locator('#result-state')).toHaveText('结果已更新');await expect(page.locator('#cnn-source')).toHaveValue('linked');
});
test('Worker 暂停、恢复、取消与任务切页10轮',async({page})=>{
  await boot(page,'optimization');for(let i=0;i<10;i++){await page.locator('#steps').fill('10000');await page.locator('#opt-run').click();await expect(page.locator('#task-bar')).toHaveClass(/visible/);await page.locator('#task-pause').click();await expect(page.locator('#task-message')).toContainText('已暂停');await page.locator('#task-pause').click();await page.locator('#task-cancel').click();await expect(page.locator('#task-bar')).not.toHaveClass(/visible/);await expect(page.locator('#toast')).toContainText('取消');}await page.locator('#steps').fill('150');await page.locator('#opt-run').click();await expect(page.locator('#result-state')).toHaveText('结果已更新');
});
test('六模块关键窄屏无整页溢出',async({page})=>{await page.setViewportSize({width:390,height:844});for(const id of ['embeddings','sequence','cnn','comparison','optimization']){await boot(page,id);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await capture(page,{path:evidencePath(`${id}-390.png`),fullPage:true});}});
